image: Visual Studio 2017

environment:
  matrix:
    - nodejs_version: '12'
      npm_version:    '6'
      DEBUG:          'tape-spawn'
      SHARP_IGNORE_GLOBAL_LIBVIPS: '1'

install:
  - ps: Install-Product node $env:nodejs_version x64
#  - ps: npm install -g "npm@${env:npm_version}"
  - npm config set script-shell "C:\\Program Files\\git\\bin\\bash.exe"
  - npm config set prefer-offline true
  - npm install
  - npm run install:all

build: off

cache:
  - '%AppData%/npm-cache'

test_script:
  - node --version
  - npm --version
  - npm test
